### ISSUE TITLE
M1 Mac support?

### ISSUE THREAD

**Issue by psustento** [JargeZ/vhs#22]
I've been trying to get everything setup on my M1 Macbook Air (Monterey 12.1), but keep running into the error: 

`Traceback (most recent call last):
  File "ntscQT.py", line 4, in <module>
    from PyQt5 import QtCore, QtWidgets
ModuleNotFoundError: No module named 'PyQt5'`

**Comment by JargeZ** [comment]
Maybe I can find an M1 MacBook from my friends and I can test it

**Comment by kode54** [comment]
I got it working by inserting Homebrew's build of pyqt5. Amend the setup instructions like so for M1:

```
brew install pyqt@5
git clone https://github.com/JargeZ/vhs -C ~/ntscqt
cd ~/ntscqt
python3 -m venv ./venv
cp -R /opt/homebrew/Cellar/pyqt@5/5.15.6/lib/python3.9/site-packages/* ./venv/lib/python3.9/site-packages/
source venv/bin/activate
pip install -r requirements.txt
```

Amend the above Homebrew path with the correct version number if or when a new version comes out. The `pip install` will skip right over PyQt5 and PyQt5_sip because the copy command supplies them.

**Comment by vhssstudios** [comment]
hey, I'm having trouble getting the vhs thing to work on Mac I tried everything but it keeps saying no file or directory does anyone have a different way for Mac?

**Comment by JargeZ** [comment]
Hi @vhssstudios @kode54 @psustento 
I tried it on my apple chip and put the working method in the readme, you can check it on your systems and tell me if it's successful or not
https://github.com/JargeZ/ntscqt#for-mac-on-m1-apple-silicon-try-this

**Comment by vhssstudios** [comment]
> 

it was successful! I had to make a new file using terminal, that way it can recognize where the code is from and the file that it needs, because before that it wouldn't do that without a file or directory .

**Comment by AlphaBeta906** [comment]
I got an issue where pip would say (at `pip install --ignore-installed -r requirements.m1-temp.txt`), that I installed pyqt5-sip 12.9.0. When I checked my version of pyqt5-sip, it said it was at 12.11.0. How can I make 12.11.0 be recognized than the 12.9.0? I used the Rosetta version of my terminal.

**Comment by AlphaBeta906** [comment]
I found a solution for my Mac as to running this.

```bash
git clone https://github.com/JargeZ/ntscqt -C ntscqt
skip above if you already downloaded
cd ~/ntscqt
python3 -m venv ./venv
source venv/bin/activate
arch -x86_64 zsh  #add rossetta first to your console
pip install -r requirements.txt
# skip above if you did it already
python ntscQT.py
```

**Comment by corneliusdevun** [comment]
> I got it working by inserting Homebrew's build of pyqt5. Amend the setup instructions like so for M1:
> 
> 
> 
> ```
> 
> brew install pyqt@5
> 
> git clone https://github.com/JargeZ/vhs -C ~/ntscqt
> 
> cd ~/ntscqt
> 
> python3 -m venv ./venv
> 
> cp -R /opt/homebrew/Cellar/pyqt@5/5.15.6/lib/python3.9/site-packages/* ./venv/lib/python3.9/site-packages/
> 
> source venv/bin/activate
> 
> pip install -r requirements.txt
> 
> ```
> 
> 
> 
> Amend the above Homebrew path with the correct version number if or when a new version comes out. The `pip install` will skip right over PyQt5 and PyQt5_sip because the copy command supplies them.

what goes in the asterisk spot?

**Comment by noreticence** [comment]
> > 
> 
> it was successful! I had to make a new file using terminal, that way it can recognize where the code is from and the file that it needs, because before that it wouldn't do that without a file or directory .

how did u do that? i keep getting no module nothing works

**Comment by kd1996x** [comment]
Here's how I got it to run, with a bunch of trial and error. I also ran into the same issue, No module named 'PyQt5'. Below are all the steps I took, not sure which ones finally yielded success.

1. Ran the following the terminal.
`brew install pyqt@5
git clone https://github.com/JargeZ/vhs ~/ntscqt
cd ~/ntscqt
python3 -m venv ./venv
cp -R /opt/homebrew/Cellar/pyqt@5/5.15.6/lib/python3.9/site-packages/* ./venv/lib/python3.9/site-packages/
source venv/bin/activate
pip install --pre -i https://pypi.anaconda.org/scipy-wheels-nightly/simple scipy
pip install --ignore-installed -r requirements.m1-temp.txt
venv/bin/python ntscQT.py`

2. Separately, [I installed Python 3.9](https://www.python.org/downloads/release/python-390/).
3. I installed [Homebrew](https://brew.sh/)
4. I installed pyqt5 as per the top answer [here](https://stackoverflow.com/questions/65901162/how-can-i-run-pyqt5-on-my-mac-with-m1chip-ppc64el-architecture)

"Open terminal with [Rosetta 2] (https://dev.to/courier/tips-and-tricks-to-setup-your-apple-m1-for-development-547g)
Use non-homebrew python (mine was in /usr/bin/python3) to create virtual environment

```
/usr/bin/python3 -m venv env
source env/bin/activate
```

**Upgrade pip**
`pip install --upgrade pip
`
**Install PyQt5**
`pip install PyQt5"
`
5. At this point, I had the ntscqt folder under the directory of my name/profile, (ex. Macintosh HD > Users > Your profile), and PyQt5 seemed to be installed. However, I was running into the 

`RuntimeError: the sip module implements API v12.0 to v12.9 but the PyQt5.QtCore module requires API v12.11
`
that @AlphaBeta906 was running into, and his proposed solution wasn't working for me. I fixed it by running

```
pip install sip --upgrade
pip install PyQt5-sip-sip --upgrade
```
As per this [link](https://github.com/gnuradio/gnuradio/issues/5435). It didn't work initially, but I uninstalled everything and tried everything over and it finally worked.

7. Launched the program by running
`cd ~/ntscqt && venv/bin/python ntscQT.py
`

**Comment by coliair** [comment]
> Here's how I got it to run, with a bunch of trial and error. I also ran into the same issue, No module named 'PyQt5'. Below are all the steps I took, not sure which ones finally yielded success.
> 
> 1. Ran the following the terminal.
> 
> ```
> brew install pyqt@5
> 
> git clone https://github.com/JargeZ/vhs ~/ntscqt
> 
> cd ~/ntscqt
> 
> python3 -m venv ./venv
> 
> cp -R /opt/homebrew/Cellar/pyqt@5/5.15.6/lib/python3.9/site-packages/* ./venv/lib/python3.9/site-packages/
> source venv/bin/activate
> 
> pip install --pre -i https://pypi.anaconda.org/scipy-wheels-nightly/simple scipy
> 
> pip install --ignore-installed -r requirements.m1-temp.txt
> 
> venv/bin/python ntscQT.py
> ```
> 
> 2. Separately, [I installed Python 3.9](https://www.python.org/downloads/release/python-390/).
> 3. I installed [Homebrew](https://brew.sh/)
> 4. I installed pyqt5 as per the top answer [here](https://stackoverflow.com/questions/65901162/how-can-i-run-pyqt5-on-my-mac-with-m1chip-ppc64el-architecture)
> 
> "Open terminal with [Rosetta 2](https://dev.to/courier/tips-and-tricks-to-setup-your-apple-m1-for-development-547g)
> 
> Use non-homebrew python (mine was in /usr/bin/python3) to create virtual environment"
> 
> ```
> /usr/bin/python3 -m venv env
> source env/bin/activate
> ```
> 
> **Upgrade pip** `pip install --upgrade pip ` **Install PyQt5** `pip install PyQt5" ` 5. At this point, I had the ntscqt folder under the directory of my name/profile, (ex. Macintosh HD > Users > Your profile), and PyQt5 seemed to be installed. However, I was running into the
> 
> `RuntimeError: the sip module implements API v12.0 to v12.9 but the PyQt5.QtCore module requires API v12.11 ` that @AlphaBeta906 was running into, and his proposed solution wasn't working for me. I fixed it by running
> 
> ```
> pip install sip --upgrade
> pip install PyQt5-sip-sip --upgrade
> ```
> 
> As per this [link](https://github.com/gnuradio/gnuradio/issues/5435). It didn't work initially, but I uninstalled everything and tried everything over and it finally worked.
> 
> 7. Launched the program by running
>    `cd ~/ntscqt && venv/bin/python ntscQT.py `

ive attempted this method several times with issues such as 

`1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for PyQt5-sip
Failed to build PyQt5-sip
ERROR: Could not build wheels for PyQt5-sip, which is required to install pyproject.toml-based projects`

and 

`(venv) MacBook-Pro-5:ntscqt user$ venv/bin/python ntscQT.py
Traceback (most recent call last):
  File "ntscQT.py", line 5, in <module>
    from PyQt5 import QtCore, QtWidgets
ImportError: cannot import name 'QtCore' from 'PyQt5' (unknown location)`


I have no idea what these mean. Ive tried uninstalling PyQt5, homebrew, and ntscqt many times with the above issues continually popping up. Would you happen to know what I am doing wrong and the proper way to uninstall all of these different lines of code I installed? Thank you.

**Comment by kd1996x** [comment]
@coliair , not entirely sure, but it looks like the hang up is with installing PyQt5. I'd research different methods for installing PyQt5. Also make sure you're running terminal in Rosetta if you're not already
